#!/usr/bin/env escript

main(_) ->
    {ok, sudoku} = compile:file(sudoku),
    {ok, unittests} = compile:file(unittests),
    {ok, sudoku} = unittests:test(),
    io:format("All tests passed :-)~n").
