#!/usr/bin/env escript

main(_) ->
    {ok, sudoku} = compile:file(sudoku),
    {ok, unittests} = compile:file(unittests),
    ok = unittests:test(),
    io:format("All tests passed :-)~n~n"),
    Input = "4.73698.563...8......7......2.....6.....8.4......1.......6.3.7.5..2.....1.4......",
    Output = sudoku:solve(Input),
    io:format("Input:  ~p~nOutput: ~p~n", [Input, Output]).
